### PR TITLE
Update LinuxBoot info diagram with Slim Bootloader included

### PR DESCRIPTION
**Pull request by LeanSheng**
Added Slim Bootloader with LinuxBoot support.
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons License</a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
Signed-off-by: Tan, Lean Sheng <lean.sheng.tan@intel.com>

### CODE REVIEW

**Comment by zaolin** [comment]
Hey @LeanSheng,

I am fine with it. Just clarify the license as a statement in the pull request.
Please pick one of the https://creativecommons.org/choose/

**Comment by LeanSheng** [comment]
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons License</a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by LeanSheng** [comment]
> Hey @LeanSheng,
> 
> I am fine with it. Just clarify the license as a statement in the pull request.
> Please pick one of the https://creativecommons.org/choose/

Is this the way? i just included the logo :)

**Comment by zaolin** [comment]
works fine for me :)

**Pull request merged**
